export const LIVE_COMMON_DATA = [
  {
    image: '/images/LiveClasses/2.Independence.svg',
    bTopColor: ' #3fc',
    bBottomColor: '#ffe0e8',
    mainHeading: 'Independence:',
    subtext: 'Your Zoom account will be used. All the features and provisions of your Zoom account shall be available with an added advantage of login restrictions only for selected students.',
  },
  {
    image: '/images/LiveClasses/3.Flexibility.webp',
    bTopColor: '#C5D4FA',
    bBottomColor: '#F2EACD',
    mainHeading: 'Flexibility:',
    subtext: 'Any number of Zoom accounts can be used. Different Zoom accounts can be mapped with different Class Sessions thus allowing multiple teachers to use their personal accounts.',
  },
  {
    image: '/images/LiveClasses/4.SecureAccess.webp',
    bTopColor: '#B9FFF1',
    bBottomColor: '#FAD4DF',
    mainHeading: 'Secure Access:',
    subtext: 'Only selected students who have access to the App can now access Zoom class, no need to share Meeting ID everytime, No random access.',
  },
  {
    image: '/images/LiveClasses/5.MultipleUses.webp',
    bTopColor: '#C7D5FA',
    bBottomColor: '#F3EBCE',
    mainHeading: 'Multiple uses of Zoom:',
    subtext: 'Zoom facility available for live Class and Doubts modules. Soon Zoom is being integrated to the online Exam module for online Exam proctoring.',
  },
  {
    image: '/images/LiveClasses/6.oraganizedContent.webp',
    bTopColor: '#B9FFF1',
    bBottomColor: '#FFD8E3',
    mainHeading: 'Organised Content:',
    subtext: 'Now you dont have to invite students by sending separate meeting notifications and reminders to parents. This will allow all the Zoom classes to be listed and seen on the students dashboard scheduled as a part of curriculum.',
  },
  {
    image: '/images/LiveClasses/7.AllowReplay.webp',
    bTopColor: '#BAFFF2',
    bBottomColor: '#FCD7E2',
    mainHeading: 'Allow Replay:',
    subtext: 'Zoom meeting recordings can be uploaded for later replay by students.',
  },
  {
    image: '/images/LiveClasses/8.AttendanceRecord.webp',
    bTopColor: '#C7D5FB',
    bBottomColor: '#F0E7CB',
    mainHeading: 'Attendance Record:',
    subtext: 'Now its possible to maintain organized record of attendance in Zoom Class along with other attendance and digital learning activity record of the student.',
  },
]